on: [push, pull_request]

jobs:
  build_docs_job:
    runs-on: ubuntu-22.04
    name: job that builds sphinx docs
    steps:
      - name: build sphinx docs
        id: build
        uses: actions/VscDocumentation@v2
      - name: show build summary
        run: echo "${{ steps.buid.outputs.summary }}"

